# Generated by Django 5.2 on 2025-09-28 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleapikeys',
            name='cse_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
